# Site settings
title: Dogeek - Portfolio
description: Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Simon Bordeyne
user_description: I'm a Software Engineer, particularly skilled with Python, data processing and GUI development. I've worked on numerous projects, and I would be excited to learn even more technologies and stacks.
user_title: Software Engineer
email: simon.bordeyne@gmail.com
twitter_username: _Dogeek_
github_username:  Dogeek
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

lsi: false
safe: true
source: "/"
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
